"""Initial schema"""

revision = 'b9257a8c23d3'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('actor_type', sa.String(length=64), nullable=False),
    sa.Column('actor_id', sa.String(length=64), nullable=True),
    sa.Column('action', sa.String(length=128), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log'))
    )
    op.create_table('automation_rules',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('rule_type', sa.String(length=64), nullable=False),
    sa.Column('conditions_json', sa.JSON(), nullable=False),
    sa.Column('actions_json', sa.JSON(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_automation_rules'))
    )
    op.create_table('chats',
    sa.Column('telegram_chat_id', sa.BigInteger(), nullable=False),
    sa.Column('chat_type', sa.String(length=32), nullable=False),
    sa.Column('is_forum', sa.Boolean(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chats')),
    sa.UniqueConstraint('telegram_chat_id', name=op.f('uq_chats_telegram_chat_id'))
    )
    op.create_table('message_links',
    sa.Column('entity_type', sa.String(length=32), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('telegram_chat_id', sa.BigInteger(), nullable=False),
    sa.Column('telegram_message_id', sa.BigInteger(), nullable=False),
    sa.Column('telegram_message_thread_id', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_message_links')),
    sa.UniqueConstraint('entity_type', 'entity_id', name=op.f('uq_message_links_entity_type')),
    sa.UniqueConstraint('telegram_chat_id', 'telegram_message_id', name=op.f('uq_message_links_telegram_chat_id'))
    )
    op.create_index('ix_message_links_entity', 'message_links', ['entity_type', 'entity_id'], unique=False)
    op.create_table('system_health',
    sa.Column('component', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('details_json', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_system_health')),
    sa.UniqueConstraint('component', name=op.f('uq_system_health_component'))
    )
    op.create_table('templates',
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_templates')),
    sa.UniqueConstraint('slug', name=op.f('uq_templates_slug'))
    )
    op.create_table('users',
    sa.Column('telegram_user_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_telegram_user_id'), 'users', ['telegram_user_id'], unique=True)
    op.create_table('weekly_plans',
    sa.Column('week_start', sa.Date(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('goals_json', sa.JSON(), nullable=False),
    sa.Column('joint_plans_json', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_weekly_plans')),
    sa.UniqueConstraint('week_start', name=op.f('uq_weekly_plans_week_start'))
    )
    op.create_table('daily_plans',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('busy_from', sa.Time(), nullable=True),
    sa.Column('busy_to', sa.Time(), nullable=True),
    sa.Column('after_work', sa.Text(), nullable=True),
    sa.Column('important_today', sa.Text(), nullable=True),
    sa.Column('joint_plan', sa.Text(), nullable=True),
    sa.Column('shopping_today', sa.Text(), nullable=True),
    sa.Column('household_evening', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_daily_plans_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_daily_plans')),
    sa.UniqueConstraint('user_id', 'date', name=op.f('uq_daily_plans_user_id'))
    )
    op.create_table('notes',
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('category_guess', sa.String(length=64), nullable=True),
    sa.Column('converted_to_entity_type', sa.String(length=32), nullable=True),
    sa.Column('converted_to_entity_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_notes_created_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notes'))
    )
    op.create_table('topics',
    sa.Column('chat_id', sa.String(length=36), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('telegram_message_thread_id', sa.BigInteger(), nullable=True),
    sa.Column('content_type', sa.String(length=64), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('message_policy', sa.String(length=64), nullable=False),
    sa.Column('autopost_rules_json', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], name=op.f('fk_topics_chat_id_chats')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_topics')),
    sa.UniqueConstraint('chat_id', 'slug', name=op.f('uq_topics_chat_id'))
    )
    op.create_index('ix_topics_chat_slug', 'topics', ['chat_id', 'slug'], unique=False)
    op.create_table('chores',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('chore_type', sa.String(length=32), nullable=False),
    sa.Column('frequency', sa.String(length=32), nullable=False),
    sa.Column('mode', sa.String(length=32), nullable=False),
    sa.Column('assigned_user_id', sa.String(length=36), nullable=True),
    sa.Column('backup_user_id', sa.String(length=36), nullable=True),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('estimated_minutes', sa.Integer(), nullable=True),
    sa.Column('priority', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('last_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('posted_message_id', sa.BigInteger(), nullable=True),
    sa.Column('topic_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assigned_user_id'], ['users.id'], name=op.f('fk_chores_assigned_user_id_users')),
    sa.ForeignKeyConstraint(['backup_user_id'], ['users.id'], name=op.f('fk_chores_backup_user_id_users')),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], name=op.f('fk_chores_topic_id_topics')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chores'))
    )
    op.create_index('ix_chores_status_due_at', 'chores', ['status', 'due_at'], unique=False)
    op.create_table('decisions',
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('options_json', sa.JSON(), nullable=False),
    sa.Column('driver_user_id', sa.String(length=36), nullable=True),
    sa.Column('approver_user_id', sa.String(length=36), nullable=True),
    sa.Column('deadline_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('final_decision', sa.Text(), nullable=True),
    sa.Column('rationale_short', sa.Text(), nullable=True),
    sa.Column('posted_message_id', sa.BigInteger(), nullable=True),
    sa.Column('topic_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['approver_user_id'], ['users.id'], name=op.f('fk_decisions_approver_user_id_users')),
    sa.ForeignKeyConstraint(['driver_user_id'], ['users.id'], name=op.f('fk_decisions_driver_user_id_users')),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], name=op.f('fk_decisions_topic_id_topics')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_decisions'))
    )
    op.create_index('ix_decisions_status_deadline', 'decisions', ['status', 'deadline_at'], unique=False)
    op.create_table('events',
    sa.Column('owner_user_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('is_joint', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('posted_message_id', sa.BigInteger(), nullable=True),
    sa.Column('topic_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], name=op.f('fk_events_owner_user_id_users')),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], name=op.f('fk_events_topic_id_topics')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_events'))
    )
    op.create_index('ix_events_date', 'events', ['date'], unique=False)
    op.create_table('purchases',
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('priority', sa.String(length=32), nullable=False),
    sa.Column('budget_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('payer_mode', sa.String(length=32), nullable=False),
    sa.Column('driver_user_id', sa.String(length=36), nullable=True),
    sa.Column('approver_user_id', sa.String(length=36), nullable=True),
    sa.Column('confirmation_required', sa.Boolean(), nullable=False),
    sa.Column('deadline_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('links_json', sa.JSON(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('posted_message_id', sa.BigInteger(), nullable=True),
    sa.Column('topic_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['approver_user_id'], ['users.id'], name=op.f('fk_purchases_approver_user_id_users')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_purchases_created_by_users')),
    sa.ForeignKeyConstraint(['driver_user_id'], ['users.id'], name=op.f('fk_purchases_driver_user_id_users')),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], name=op.f('fk_purchases_topic_id_topics')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_purchases'))
    )
    op.create_index('ix_purchases_status', 'purchases', ['status'], unique=False)
    op.create_table('reminders',
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('target_user_id', sa.String(length=36), nullable=True),
    sa.Column('target_chat_id', sa.String(length=36), nullable=True),
    sa.Column('target_topic_id', sa.String(length=36), nullable=True),
    sa.Column('cron_expr', sa.String(length=128), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('quiet_hours_json', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['target_chat_id'], ['chats.id'], name=op.f('fk_reminders_target_chat_id_chats')),
    sa.ForeignKeyConstraint(['target_topic_id'], ['topics.id'], name=op.f('fk_reminders_target_topic_id_topics')),
    sa.ForeignKeyConstraint(['target_user_id'], ['users.id'], name=op.f('fk_reminders_target_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reminders'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reminders')
    op.drop_index('ix_purchases_status', table_name='purchases')
    op.drop_table('purchases')
    op.drop_index('ix_events_date', table_name='events')
    op.drop_table('events')
    op.drop_index('ix_decisions_status_deadline', table_name='decisions')
    op.drop_table('decisions')
    op.drop_index('ix_chores_status_due_at', table_name='chores')
    op.drop_table('chores')
    op.drop_index('ix_topics_chat_slug', table_name='topics')
    op.drop_table('topics')
    op.drop_table('notes')
    op.drop_table('daily_plans')
    op.drop_table('weekly_plans')
    op.drop_index(op.f('ix_users_telegram_user_id'), table_name='users')
    op.drop_table('users')
    op.drop_table('templates')
    op.drop_table('system_health')
    op.drop_index('ix_message_links_entity', table_name='message_links')
    op.drop_table('message_links')
    op.drop_table('chats')
    op.drop_table('automation_rules')
    op.drop_table('audit_log')
    # ### end Alembic commands ###

